USE [C:\USERS\BUTEA\VSPROJECTS\PHARMACYISS\PHARMACYISS\PHARMACY\PHARMACYDB.MDF]


CREATE TABLE [dbo].[Account]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Username] VARCHAR(40) NOT NULL,
	[Password] VARCHAR(40) NOT NULL,
	[Unit] VARCHAR(40) NOT NULL
)

CREATE TABLE [dbo].[Employee]
(
	[ID] INT NOT NULL PRIMARY KEY,
	[AccountID] INT NOT NULL FOREIGN KEY REFERENCES [Account](ID),
	[Name] VARCHAR(40) NOT NULL,
	[Salary] INT NOT NULL CHECK (Salary >= 0),
	[Title] VARCHAR(25) NOT NULL,
	[HireDate] DATE NOT NULL,
)


CREATE TABLE [dbo].[Medicine]
(
	[ID] INT NOT NULL PRIMARY KEY,
	[Name] VARCHAR(30) NOT NULL,
	[PackSize] INT NOT NULL,
)

CREATE TABLE [dbo].[Order]
(
	[ID] INT NOT NULL PRIMARY KEY,
	[ETA] DATETIME
)

CREATE TABLE [dbo].[MedicineOrder]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[MedicineID] INT NOT NULL FOREIGN KEY REFERENCES [Medicine](ID),
	[OrderID] INT NOT NULL FOREIGN KEY REFERENCES [Order](ID),
	[Quantity] INT NOT NULL CHECK (Quantity > 0)
)

